languages = {
    'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'armenian': 'hy', 'assamese': 'as',
    'aymara': 'ay', 'azerbaijani': 'az', 'bambara': 'bm', 'basque': 'eu', 'belarusian': 'be', 'bengali': 'bn',
    'bhojpuri': 'bho', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca', 'cebuano': 'ceb', 'chichewa': 'ny',
    'chinese (simplified)': 'zh-CN', 'chinese (traditional)': 'zh-TW', 'corsican': 'co', 'croatian': 'hr',
    'czech': 'cs', 'danish': 'da', 'dhivehi': 'dv', 'dogri': 'doi', 'dutch': 'nl', 'english': 'en',
    'esperanto': 'eo', 'estonian': 'et', 'ewe': 'ee', 'filipino': 'tl', 'finnish': 'fi', 'french': 'fr',
    'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka', 'german': 'de', 'greek': 'el', 'guarani': 'gn',
    'gujarati': 'gu', 'haitian creole': 'ht', 'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'iw', 'hindi': 'hi',
    'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig', 'ilocano': 'ilo', 'indonesian': 'id',
    'irish': 'ga', 'italian': 'it', 'japanese': 'ja', 'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk',
    'khmer': 'km', 'kinyarwanda': 'rw', 'konkani': 'gom', 'korean': 'ko', 'krio': 'kri',
    'kurdish (kurmanji)': 'ku', 'kurdish (sorani)': 'ckb', 'kyrgyz': 'ky', 'lao': 'lo', 'latin': 'la',
    'latvian': 'lv', 'lingala': 'ln', 'lithuanian': 'lt', 'luganda': 'lg', 'luxembourgish': 'lb',
    'macedonian': 'mk', 'maithili': 'mai', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml', 'maltese': 'mt',
    'maori': 'mi', 'marathi': 'mr', 'meiteilon (manipuri)': 'mni-Mtei', 'mizo': 'lus', 'mongolian': 'mn',
    'myanmar': 'my', 'nepali': 'ne', 'norwegian': 'no', 'odia (oriya)': 'or', 'oromo': 'om', 'pashto': 'ps',
    'persian': 'fa', 'polish': 'pl', 'portuguese': 'pt', 'punjabi': 'pa', 'quechua': 'qu', 'romanian': 'ro',
    'russian': 'ru', 'samoan': 'sm', 'sanskrit': 'sa', 'scots gaelic': 'gd', 'sepedi': 'nso', 'serbian': 'sr',
    'sesotho': 'st', 'shona': 'sn', 'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk', 'slovenian': 'sl',
    'somali': 'so', 'spanish': 'es', 'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv', 'tajik': 'tg',
    'tamil': 'ta', 'tatar': 'tt', 'telugu': 'te', 'thai': 'th', 'tigrinya': 'ti', 'tsonga': 'ts',
    'turkish': 'tr', 'turkmen': 'tk', 'twi': 'ak', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug',
    'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh', 'yiddish': 'yi', 'yoruba': 'yo',
    'zulu': 'zu'}

turkish_provinces = [
    {"name_own": 'Adana', "districts": 15, "communities": 15, "urban_villages": 829},
    {"name_own": 'Adiyaman', "districts": 9, "communities": 23, "urban_villages": 172, "villages": 451},
    {"name_own": 'Afyonkarahisar', "districts": 18, "communities": 59, "urban_villages": 436, "villages": 423},
    {"name_own": 'Pain', "districts": 8, "communities": 12, "urban_villages": 99, "villages": 562},
    {"name_own": 'Amasya', "districts": 7, "communities": 8, "urban_villages": 107, "villages": 372},
    {"name_own": 'Ankara', "districts": 25, "communities": 25, "urban_villages": 1433},
    {"name_own": 'Antalya', "districts": 19, "communities": 19, "urban_villages": 910},
    {"name_own": 'Artvin', "districts": 9, "communities": 9, "urban_villages": 38, "villages": 320},
    {"name_own": 'Aydin', "districts": 17, "communities": 17, "urban_villages": 670},
    {"name_own": 'Balıkesir', "districts": 20, "communities": 20, "urban_villages": 1129},
    {"name_own": 'Bilecik', "districts": 8, "communities": 11, "urban_villages": 60, "villages": 245},
    {"name_own": 'Bitlis', "districts": 7, "communities": 13, "urban_villages": 123, "villages": 348},
    {"name_own": 'Bolu', "districts": 9, "communities": 12, "urban_villages": 93, "villages": 487},
    {"name_own": 'Burdur', "districts": 11, "communities": 14, "urban_villages": 126, "villages": 193},
    {"name_own": 'Bursa', "districts": 17, "communities": 17, "urban_villages": 1060},
    {"name_own": 'Çanakkale', "districts": 12, "communities": 23, "urban_villages": 81, "villages": 574},
    {"name_own": 'Çankırı', "districts": 12, "communities": 15, "urban_villages": 91, "villages": 376},
    {"name_own": 'Corum', "districts": 14, "communities": 16, "urban_villages": 124, "villages": 760},
    {"name_own": 'Denizlic', "districts": 19, "communities": 19, "urban_villages": 624},
    {"name_own": 'Diyarbakir', "districts": 17, "communities": 17, "urban_villages": 1041},
    {"name_own": 'Edirne', "districts": 9, "communities": 16, "urban_villages": 94, "villages": 254},
    {"name_own": 'Elazig', "districts": 11, "communities": 20, "urban_villages": 149, "villages": 552},
    {"name_own": 'Erzincan', "districts": 9, "communities": 24, "urban_villages": 148, "villages": 528},
    {"name_own": 'Erzurum', "districts": 20, "communities": 20, "urban_villages": 1177},
    {"name_own": 'Eskişehir', "districts": 14, "communities": 14, "urban_villages": 539},
    {"name_own": 'Gaziantep', "districts": 9, "communities": 9, "urban_villages": 785},
    {"name_own": 'Giresun', "districts": 16, "communities": 24, "urban_villages": 193, "villages": 551},
    {"name_own": 'Gumushane', "districts": 6, "communities": 14, "urban_villages": 70, "villages": 321},
    {"name_own": 'Hakkari', "districts": 4, "communities": 8, "urban_villages": 53, "villages": 125},
    {"name_own": 'Hatay', "districts": 15, "communities": 15, "urban_villages": 590},
    {"name_own": 'Isparta', "districts": 13, "communities": 22, "urban_villages": 217, "villages": 203},
    {"name_own": 'Mersin', "districts": 13, "communities": 13, "urban_villages": 805},
    {"name_own": 'Istanbul Real Estate', "districts": 39, "urban_villages": 39, "villages": 960},
    {"name_own": 'İzmir', "districts": 30, "communities": 30, "urban_villages": 1295},
    {"name_own": 'Kars', "districts": 8, "communities": 9, "urban_villages": 56, "villages": 380},
    {"name_own": 'Kastamonu', "districts": 20, "communities": 20, "urban_villages": 162, "villages": 1065},
    {"name_own": 'Kayseri', "districts": 16, "communities": 16, "urban_villages": 758},
    {"name_own": 'Kırklareli', "districts": 8, "communities": 21, "urban_villages": 107, "villages": 179},
    {"name_own": 'Kırşehir', "districts": 7, "communities": 10, "urban_villages": 67, "villages": 252},
    {"name_own": 'Kocaeli', "districts": 12, "communities": 12, "urban_villages": 474},
    {"name_own": 'Konya', "districts": 31, "communities": 31, "urban_villages": 1196},
    {"name_own": 'Kutahya', "districts": 12, "communities": 2, "urban_villages": 223, "villages": 548},
    {"name_own": 'Malatya', "districts": 13, "communities": 13, "urban_villages": 717},
    {"name_own": 'Manisa', "districts": 17, "communities": 17, "urban_villages": 1088},
    {"name_own": 'Kahramanmaraş', "districts": 11, "communities": 11, "urban_villages": 693},
    {"name_own": 'Mardin', "districts": 10, "communities": 10, "urban_villages": 696},
    {"name_own": 'Muğla', "districts": 13, "communities": 13, "urban_villages": 565},
    {"name_own": 'Mus', "districts": 6, "communities": 23, "urban_villages": 110, "villages": 366},
    {"name_own": 'Nevsehir', "districts": 8, "communities": 23, "urban_villages": 125, "villages": 153},
    {"name_own": 'Nowhere', "districts": 6, "communities": 29, "urban_villages": 138, "villages": 132},
    {"name_own": 'exploring', "districts": 19, "communities": 19, "urban_villages": 741},
    {"name_own": 'Rize', "districts": 12, "communities": 18, "urban_villages": 202, "villages": 291},
    {"name_own": 'sakarya', "districts": 16, "communities": 16, "urban_villages": 665},
    {"name_own": 'Samsung', "districts": 17, "communities": 17, "urban_villages": 1245},
    {"name_own": 'Siirt', "districts": 7, "communities": 12, "urban_villages": 63, "villages": 277},
    {"name_own": 'Sinop', "districts": 9, "communities": 9, "urban_villages": 55, "villages": 470},
    {"name_own": 'Sivas', "districts": 17, "communities": 24, "urban_villages": 246, "villages": 1240},
    {"name_own": 'Tekirdag', "districts": 11, "communities": 11, "urban_villages": 355},
    {"name_own": 'Tokat', "districts": 12, "communities": 37, "urban_villages": 308, "villages": 623},
    {"name_own": 'Trabzon', "districts": 18, "communities": 18, "urban_villages": 692},
    {"name_own": 'Tunceli', "districts": 8, "communities": 9, "urban_villages": 43, "villages": 361},
    {"name_own": 'Şanlıurfa', "districts": 13, "communities": 13, "urban_villages": 1380},
    {"name_own": 'Servant', "districts": 6, "communities": 12, "urban_villages": 62, "villages": 256},
    {"name_own": 'From', "districts": 13, "communities": 13, "urban_villages": 685},
    {"name_own": 'Yozgat', "districts": 14, "communities": 33, "urban_villages": 219, "villages": 572},
    {"name_own": 'Zonguldak', "districts": 8, "communities": 25, "urban_villages": 176, "villages": 380},
    {"name_own": 'Aksaray', "districts": 8, "communities": 22, "urban_villages": 153, "villages": 177},
    {"name_own": 'Bayburt', "districts": 3, "communities": 5, "urban_villages": 28, "villages": 170},
    {"name_own": 'Karaman', "districts": 6, "communities": 11, "urban_villages": 130, "villages": 159},
    {"name_own": 'Kırıkkale', "districts": 9, "communities": 11, "urban_villages": 85, "villages": 185},
    {"name_own": 'Batman', "districts": 6, "communities": 11, "urban_villages": 126, "villages": 284},
    {"name_own": 'Sirnak', "districts": 7, "communities": 19, "urban_villages": 90, "villages": 102},
    {"name_own": 'Bart', "districts": 4, "communities": 8, "urban_villages": 48, "villages": 265},
    {"name_own": 'Ardahan', "districts": 6, "communities": 7, "urban_villages": 39, "villages": 227},
    {"name_own": 'Igdir', "districts": 4, "communities": 7, "urban_villages": 36, "villages": 161},
    {"name_own": 'Yalova', "districts": 6, "communities": 14, "urban_villages": 50, "villages": 43},
    {"name_own": 'Karabuk', "districts": 6, "communities": 7, "urban_villages": 78, "villages": 278},
    {"name_own": 'Kilis', "districts": 4, "communities": 4, "urban_villages": 88, "villages": 137},
    {"name_own": 'Osmaniye', "districts": 7, "communities": 17, "urban_villages": 132, "villages": 160},
    {"name_own": 'Duzce', "districts": 8, "communities": 10, "urban_villages": 114, "villages": 279}
]
